### ISSUE TITLE
Set All Cuts to 100% Doesn’t Work

### ISSUE THREAD

**Issue by Nzii3** [YimMenu-Lua/Casino-Pacino#17]
Setting all cuts to 100% raises an invalid data error when completing the heist and doesn’t give the money to the players who got the error. I did this with a friend and i got the error every time, but my friend got the error half of the time. We set the cuts to 100% before setting the entrance and exit stuff.

**Comment by Nzii3** [comment]
![IMG_5975](https://github.com/user-attachments/assets/dd11fd63-573a-4a84-9c7c-6b2dee134cd4)

**Comment by Nzii3** [comment]
We were getting 4 mill each run so maybe that is over a limit of the game?

**Comment by ShinyWasabi** [comment]
Transaction limit for Casino Heist is GTA$3,619,000.

**Comment by Nzii3** [comment]
> Transaction limit for Casino Heist is GTA$3,619,000.

Per person? @ShinyWasabi

**Comment by ShinyWasabi** [comment]
It's not about person. If you fire a transaction (SERVICE_EARN_CASINO_HEIST_FINALE in this case) with a price higher than the limit, the server will just reject it and you will get that error.

**Comment by Nzii3** [comment]
@ShinyWasabi So how much can we get per person (in total) when setting all cuts to 100%?

**Comment by Nzii3** [comment]
Or how much can we take from the vault without getting that error when having 100/100

**Comment by Nzii3** [comment]
Never mind I figured this out
