### ISSUE TITLE
Rig Casino For Session

### ISSUE THREAD

**Issue by Nzii3** [YimMenu-Lua/Casino-Pacino#19]
How can I rig the casino for the entire session or other players? I know other menus have this option but I want to make my friends some quick money.

**Comment by Nzii3-smartest-discord-moderator** [comment]
@Nzii3 your mom had skill issue under my table that's why I knocked out her teeth

**Comment by Nzii3** [comment]
> @Nzii3 your mom had skill issue under my table that's why I knocked out her teeth

No way you created an alt account bro you are sooooo mad get a job 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😭😭😭😭💀

**Comment by Nzii3** [comment]
Keep crying 😭😭😭
