### ISSUE TITLE
Error while using the script (BAD METRIC)

### ISSUE THREAD

**Issue by LunarN0v4** [YimMenu-Lua/Casino-Pacino#3]
While using this script with YimMenu, I get this error constantly and the script doesn't seem to work regardless of the script and `json.lua` successfully loading according to the console.
`[07:10:09.5475795][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":0,"char":{"slot":0,"cash":186,"bank":13696445,"evc":13696631,"pvc":0,"pxr":125000000.00000,"nonce":638384802059302561},"c":[1131.52966,250.88699,-51.29090],"pt":102063324,"vct":1640992761,"vcp":1000000,"mid":0,"action":"SELL_CHIPS","cat":"BETTING"`

**Comment by gir489returns** [comment]
And?

**Comment by LunarN0v4** [comment]
> And?

The script loads properly and this is the only warning/error that appears when using the machines or tables at the casino?

**Comment by gir489returns** [comment]
> > And?
> 
> The script loads properly and this is the only warning/error that appears when using the machines or tables at the casino when the script doesn't seem to work at all?

Can't reproduce, warnings are expected.
