### ISSUE TITLE
Dosnt work :(

### ISSUE THREAD

**Issue by genisis-1** [YimMenu-Lua/Casino-Pacino#6]
dosnt work with yim

**Comment by TwystedMind** [comment]
This script does still work, I used it as recently as 5:00 AM this morning (January 4th, 2024).

Ensure you are installing the script correctly.  You need to make sure to add **both** the "CasinoPacino.lua" and "json.lua" to the YimMenu "scripts" folder in order for it to work properly.  It will then appear under Network > Casino in YimMenu (assuming you are using the CasinoPacino script alone, and not paired with the "Alestarov Menu", in which case, it would be under Alestarov > Money > Casino).

As a note, the "scripts" folder is located at:  C:\Users\_YourUser_\AppData\Roaming\YimMenu\Scripts

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/0376ed86-73b8-4f22-88ee-7bda97a38d28)
![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/0025d0a2-9db5-4904-9b0a-2a60ee405717)
![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/d74d67f3-81a3-4100-9624-84a98427f47e)

Cannot reproduce.
