### ISSUE TITLE
Heist Editor Doesn't Work

### ISSUE THREAD

**Issue by Rxann** [YimMenu-Lua/Casino-Pacino#9]
Well, it works but when I walk near it, it doesn't show the popup to start the mission so the boards are just kind of there...

**Comment by gir489returns** [comment]
Are you a CEO?

**Comment by Rxann** [comment]
> Are you a CEO?

Once I get home I will test.

**Comment by Rxann** [comment]
> Are you a CEO?

I am incredibly mental slow.

**Comment by gir489returns** [comment]
> > Are you a CEO?
> 
> I am incredibly mental slow.

I have done this many times before, only for me to google the issue and feel the same way. It's OK to make a mistake. It's not OK to make the same mistake twice.
